scrape_configs:
- job_name: coinspeed
  scrape_interval: 10s
  static_configs:
  - targets:
    - 127.0.0.1:2112

remote_write:
- url: https://prometheus-us-central1.grafana.net/api/prom/push
  basic_auth:
    username: 58733
    password: eyJrIjoiMmVlNzRiMDM5ODMwMDY0ZmYzNTM1Zjc3MTk1NzJjZDg1NDNiMWIyMiIsIm4iOiJjb2luc3BlZWQiLCJpZCI6NDcyMTA5fQ==
